apiVersion: bundle.gravitational.io/v2
kind: Bundle
metadata:
  name: mattermost
  resourceVersion: "2.2.0"
logo: http://about.mattermost.com/wp-content/uploads/2016/01/logo.png
endpoints:
  - name: "Mattermost"
    description: "Mattermost application"
    selector:
      role: mattermost-worker
    protocol: http
  - name: "Setup"
    serviceName: bandwagon
    hidden: true
providers:
  aws:
    regions:
      - us-east-2
installer:
  setupEndpoints:
    - "Setup"
  flavors:
    prompt: "How many nodes do you want?"
    items:
      - name: "single"
        description: "A single node"
        nodes:
          - profile: worker
            count: 1
      - name: "double"
        description: "A two-node cluster"
        nodes:
          - profile: worker
            count: 2
      - name: "triple"
        description: "A three-node cluster"
        nodes:
          - profile: worker
            count: 3
nodeProfiles:
  - name: worker
    description: "Simple Mattermost Server"
    requirements:
      cpu:
        min: 1
      ram:
        min: "2GB"
    providers:
      aws:
        instanceTypes:
          - m4.xlarge
hooks:
  install:
    job: file://install.yaml
systemOptions:
  runtime:
    version: 5.0.0-beta.1
  docker:
    storageDriver: overlay2
