apiVersion: v1
kind: Application
metadata:
  name: Mattermost App
  resourceVersion: "1.0"
  releaseNotes: |
    <ul>
      <li>First Release</li>
    </ul>
  logo:
    backgroundImage: url("https://about.mattermost.com/wp-content/uploads/2016/01/logo.png")
base: gravitational.io/k8s-aws:0.0.0+latest
installer:
  provisioners:
    onprem:
      variables:
        docker:
          backend: overlay
  servers:
    worker:
      description: "Simple Mattermost Server"
      cpu:
        min_count: 4
      ram:
        min_total_mb: 2048
  flavors:
    title: "How many nodes do you want?"
    items:
      - name: "single"
        description: ""
        threshold:
          value: 1
          label: "1"
        profiles:
          worker: 1
  final_install_step:
    service_name: bandwagon
