apiVersion: v1
kind: Application
metadata:
  name: mattermost
  resourceVersion: "2.2.0"
  repository: gravitational.io
  releaseNotes: |
    <ul>
      <li>First Release</li>
    </ul>
  logo:
    backgroundImage: url("https://about.mattermost.com/wp-content/uploads/2016/01/logo.png")
base: gravitational.io/k8s-aws:0.0.0+latest
installer:
  provisioners:
    onprem:
      variables:
        docker:
          backend: overlay
  servers:
    worker:
      description: "Simple Mattermost Server"
      cpu:
        min_count: 4
      ram:
        min_total_mb: 2048
      instance_types:
        aws_terraform:
          - c3.4xlarge
  flavors:
    title: "How many nodes do you want?"
    items:
      - name: "single"
        description: ""
        threshold:
          value: 1
          label: "1"
        profiles:
          worker: 1
  final_install_step:
    service_name: bandwagon
endpoints:
  - name: "Mattermost"
    description: "Mattermost application"
    selector:
      role: mattermost-worker
    protocol: http
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: install
      spec:
        template:
          metadata:
            name: install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: install
                image: gravitational/debian-tall:0.0.1
                command:
                  - /usr/local/bin/kubectl
                  - create
                  - -f
                  - /var/lib/gravity/resources/mattermost-config.yaml
                  - -f
                  - /var/lib/gravity/resources/postgres-service.yaml
                  - -f
                  - /var/lib/gravity/resources/worker-service.yaml
                  - -f
                  - /var/lib/gravity/resources/postgres.yaml
                  - -f
                  - /var/lib/gravity/resources/worker.yaml
