apiVersion: bundle.gravitational.io/v2
kind: Bundle
metadata:
  name: mattermost
  resourceVersion: "2.2.0"
logo: http://about.mattermost.com/wp-content/uploads/2016/01/logo.png
endpoints:
  - name: "Mattermost"
    description: "Mattermost application"
    selector:
      role: mattermost-worker
    protocol: http
  - name: "Setup"
    serviceName: bandwagon
    hidden: true
providers:
  aws:
    regions:
      - us-west-2
      - us-east-1
      - eu-central-1
installer:
  setupEndpoints:
    - "Setup"
  flavors:
    prompt: "How many nodes do you want?"
    items:
      - name: "single"
        description: ""
        nodes:
          - profile: worker
            count: 1
nodeProfiles:
  - name: worker
    description: "Simple Mattermost Server"
    requirements:
      cpu:
        min: 1
      ram:
        min: "2GB"
    providers:
      aws:
        instanceTypes:
          - c3.4xlarge
hooks:
  install:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: install
      spec:
        template:
          metadata:
            name: install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: install
                image: quay.io/gravitational/debian-tall:0.0.1
                command:
                  - /usr/local/bin/kubectl
                  - create
                  - -f
                  - /var/lib/gravity/resources/mattermost.yaml
                  - --namespace
                  - default
systemOptions:
  docker:
    storageDriver: overlay
