# mattermost postgres worker
apiVersion: v1
kind: Pod
metadata:
  name: mattermost-database
  labels:
    app: mattermost
    role: mattermost-database
spec:
  containers:
  - name: mattermost-postgres
    image: apiserver:5000/postgres:9.4.4
    ports:
      - containerPort: 5432
